### PR TITLE
feat(KFLUXUI-217): add contexts to show page

### PR DESCRIPTION
**Pull request by CryptoRodeo**
- Add the context values to the integration show page.
- Add a modal to allow easy edits.
- Use spinner for loading instead of text.

backport of https://github.com/openshift/hac-dev/pull/1008

### CODE REVIEW

**Comment by CryptoRodeo** [comment]
Relies on https://github.com/konflux-ci/konflux-ui/pull/25

**Comment by CryptoRodeo** [comment]
I will rebase this soon now that the dependent MR has been merged.

**Comment by CryptoRodeo** [comment]
Converted to draft for now so I can add some spec tests for `formatContexts`

**Comment by CryptoRodeo** [comment]
Code coverage check should be safe to ignore IMO. I added an additional test to improve it. The other lines should be safe to ignore.

**Review by JoaoPedroPP — APPROVED** [review]

**Comment by JoaoPedroPP** [comment]
LGTM

**Comment by CryptoRodeo** [comment]
@sahil143 **Quick question**: Only certain people can merge, correct? This PR has been approved, but when I click the "Merge when ready" button it appears that the merge queue times out and the commit cannot be merged.

I'm going to assume I don't have the correct permissions to merge, even with that button being available.

**Comment by StanislavJochman** [comment]
LGTM.

**Comment by testcara** [comment]
LGTM

**Comment by sahil143** [comment]
> @sahil143 **Quick question**: Only certain people can merge, correct? This PR has been approved, but when I click the "Merge when ready" button it appears that the merge queue times out and the commit cannot be merged.
> 
> I'm going to assume I don't have the correct permissions to merge, even with that button being available.

Merge queue waits for this `Red Hat Konflux / konflux-ui-on-pull-request` check to pass. I don't think it can run in a merge queue because once PR is added to merge queue, a temporary branch is created and all the checks start again. Konflux checks just times out and PR is removed from the queue. I am figuring out a work around for this.

**Pull request merged**
