### PR TITLE
fix(KFLUXBUGS-96): make the secret forms more clear 

### PR DESCRIPTION
**Pull request by JoaoPedroPP**
Migration of KFLUXBUGS-96 to the new repo.

Assure during the migration we move our latest changes.

### CODE REVIEW

**Comment by JoaoPedroPP** [comment]
All local tests passed

image

**Comment by caugello** [comment]
I would keep the commit msg same as in hac-dev repo, will be easier to understand when reading the history.

**Comment by JoaoPedroPP** [comment]
> I would keep the commit msg same as in hac-dev repo, will be easier to understand when reading the history.

Commit message changed to the original

**Review by CryptoRodeo — APPROVED** [review]

**Pull request merged**
